name: scenariomanager
main: scenariomanager\Main
api: [2.0.0]
version: "1.0.0"
author: BoyIsDino
commands:
    scenario:
         description: /scenario <add:remove>
   
   finalheal:
          description: /finalheal scenario command
